In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
nt = pd.read_excel('./report.xlsx', sheet_name='tags_report')
np = pd.read_excel('./report.xlsx', sheet_name='projects_report')
nc = pd.read_excel('./report.xlsx', sheet_name='clients_report')

In [3]:
main_excel_path = './data'

In [4]:
df = pd.read_excel(f'{main_excel_path}/New tags and projects list_Toggl.xlsx', sheet_name='1.2-User-specific tags',
                   index_col='Activity type')
tags_format = pd.read_excel(f'{main_excel_path}/New tags and projects list_Toggl.xlsx', sheet_name='Tags - Format')
projects = pd.read_excel(f'{main_excel_path}/New tags and projects list_Toggl.xlsx', sheet_name='Projects')
clients = pd.read_excel(f'{main_excel_path}/New tags and projects list_Toggl.xlsx', sheet_name='Client Name').rename(columns={'Client Name': 'name'})

In [5]:
tags_format

,Tags - Format,Update Date,Comment
0,Format: Individual work,01.07.2025,0
1,Format: Meeting Internal,01.07.2025,rename 08.06.2026 (Format: Internal meeting)
2,Format: Meeting with Vendor,01.07.2025,0
3,Format: Meeting with Lab,01.07.2025,0
4,Format: Meeting with Hospital,09.12.2025,0

In [6]:
tags_format['Old name'] = tags_format['Comment'].str.extract(r'\((.*?)\)')

In [7]:
clients['Old name'] = clients['Comment (old name)'].str.extract(r'\((.*?)\)')
clients

,name,Update Date,Comment (old name),Old name
0,Abbott,01.07.2025,0,NaN
1,Alrijne,01.07.2025,0,NaN
2,BC Europe&UK,09.12.2025,0,NaN
3,BC FR CHU BRDX,09.12.2025,rename 26.05.2026 (BC Fr Bordeaux),BC Fr Bordeaux
4,BC Global,18.03.2026,rename 26.05.2026 (BC GP),BC GP
5,BC IRL Cork&Kerry,01.07.2025,rename 26.05.2026 (BC Cork&Kerry),BC Cork&Kerry
6,BC IRL NWT,26.05.2026,need to add (new),new
7,BC UK 6S,09.12.2025,rename 26.05.2026 (BC 6S),BC 6S
8,BC UK MSC,01.07.2025,rename 26.05.2026 (BC MSC),BC MSC
9,BC UK SWLP,01.07.2025,rename 26.05.2026 (BC SWLP),BC SWLP
10,BC UK WoE,01.07.2025,rename 26.05.2026 (BC WoE),BC WoE
11,Certe,01.07.2025,0,NaN
12,Dicoon,09.12.2025,0,NaN
13,GCG,01.07.2025,0,NaN
14,Labexa,01.07.2025,0,NaN
15,Potential Client,01.10.2025,0,NaN
16,Regiolab,09.12.2025,0,NaN
17,Siemens-Bernhoven,01.07.2025,0,NaN
18,StreekLab,01.07.2025,0,NaN

In [8]:
df

,New Name,Stages,Type 1,Type 2,ANAS,NIAL,SMVE,AMAN,DIDA,AIVI,NIRO,VAEL,BODM,KAAN,KURO,CHAL,BADA,LAOK,PRAR,TODA,New AT definition,OLD AT definition
Activity type,,,,,,,,,,,,,,,,,,,,,,
AT: Assessment on site,NaN,Functional,Client-oriented,billable,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Оценка на месте: сбор данных и наблюдение для ...,NaN
AT: Bank operations,NaN,Functional,Internal,Non-billable,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Банковские операции (выплата зар.плат, проведе...",NaN
AT: Business requirements,NaN,Functional,Internal,Non-billable,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,Согласование бизнес-требований и формирование ...,NaN
AT: Business trip,AT: Travel,Functional,?,?,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"Деловые поездки и командировки, считается врем...",NaN
AT: Calculations and visualization,NaN,Stage,Client-oriented,billable,1.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,Активность по выполнению расчетов и созданию в...,NaN
AT: Cito List,NaN,Deliverable,Client-oriented,billable,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,"Согласование и сопровождение списка тестов, по...",NaN
AT: Client's data handling,NaN,Stage,Client-oriented,billable,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,1.0,"Обработка ""сырых"" данных , полученных от клиен...",NaN
AT: Commercialization,AT: Marketing,Functional,Internal,Non-billable,1.0,1,1.0,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,"Разработка брошюр, презентаций, постеров и ста...",NaN
AT: Contract,AT: Commercial,Functional,Client-oriented,billable,1.0,1,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,"Подготовка прайс-листов, коммерческих предложе...",NaN
AT: Contract Heatmap,NaN,Deliverable,Client-oriented,billable,1.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Активность по визуализации и анализу распредел...,NaN
AT: Data&Systems,NaN,Stage,?,?,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,Тег для отдела BI: Работа с данными и настройк...,Работа с данными и настройка систем: разработк...
AT: Data Research,NaN,Stage,Client-oriented,Non-billable,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Анализ полученных данных и принятие решений по...,"Изучение и анализ полученных данных (файлов, д..."
was nothing,AT: Demo,Functional,Client-oriented,billable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Демонстрация Background IP продуктов и разъясн...,NaN
AT: Design,NaN,Functional,Internal,Non-billable,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,same as earlier,Поддержание внутренних библиотек иконок и анал...
AT: Ecosystem of Systems,not need,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Планирование, написание требований и участие в..."
was nothing,AT: Education,Functional,Internal,Non-billable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Прохождение курсов и обучающих программ, посещ...",NaN
AT: HR management,NaN,Functional,Internal,Non-billable,1.0,1,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,Постановка и распределение задач внутри команд...,Активность по управлению и координации работы ...
AT: HR recruiting,NaN,Functional,Internal,Non-billable,1.0,1,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,"Составление описаний вакансий, просмотр резюме...","Составление описаний вакансий, просмотр резюме..."
was nothing,AT: Onboarding,Functional,Internal,Non-billable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Организация и проведение вводного обучения нов...,NaN
AT: Internal Admin,NaN,Functional,Internal,Non-billable,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"Ведение и актуализация Toggl, планирование и с...","Ведение таблиц и трекеров, планирование и согл..."
AT: Internal reports,AT: Financial-Admin,Functional,Internal,Non-billable,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,same as earlier,"Формирование финансовых отчетов, сбор первично..."
AT: Invoicing,NaN,Functional,Internal,Non-billable,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Формирование таблиц с описаниями трат в команд...,Формирование таблиц с описаниями трат в команд...
AT: Lab-Data ARAB,NaN,Stage,Internal,Non-billable,1.0,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,Наполнение глобального каталога: исследование ...
AT: Lab-Data Matching,NaN,Stage,Client-oriented,billable,1.0,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,"Мэтчинг данных: аналиты, биоматериалы, анализа..."
AT: Lab-Data Technical Charts,NaN,Stage,Client-oriented,billable,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,Полный цикл работы с техническими картами: фор...
AT: Lab-Efficiency-Workshop,not need (see AT: Demo),NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Тренинг для клиентов по концепции GCG: подгото...
AT: Lab-Flow,not need,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,"Аналитика потоков в лаборатории, разработка те..."
AT: Lab-Horizontals,NaN,Deliverable,Client-oriented,billable,1.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,"Сбор, структурирование и заполнение данных по ...",Организация лаборатории в соответствии с гориз...
AT: Lab-Modeling,not need (see Project suffix),NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,Проведение моделирования процессов лаборатории...
AT: Local-Catalog,NaN,Stage,Client-oriented,billable,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Подготовка данных для импорта и создания сущно...
AT: Make-up,NaN,Stage,Client-oriented,billable,1.0,1,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Оформление: дизайн, форматирование, приведение..."
AT: Methodology,NaN,Functional,Internal,Non-billable,1.0,1,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,"Разработка, описание и актуализация подходов, ..."
AT: ML,not need,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,"Постановка задач и подготовка данных для ML, у..."
AT: N/A,NaN,NaN,NaN,NaN,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,"Not Applicable. Выбирать, если ни один из суще..."
AT: Office maintenance,NaN,Functional,Internal,Non-billable,1.0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Закупка расходных материлов для офиса (канцеля...
was nothing,AT: Team-Events,Functional,Internal,Non-billable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Подготовка и участие в командных мероприятиях:...,NaN
AT: Pre-Invoicing,not need,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Подготовка документов из командировок (чеков, ..."
AT: Presale,not need (see Potential Client: Project),NaN,NaN,NaN,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,Подготовка информации для клиентов перед заклю...
AT: Presentations,NaN,Stage,?,?,1.0,1,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,Создание и редактирование презентаций: подгото...,Подготовка презентаций.
AT: Project-Management,NaN,Functional,?,?,1.0,1,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,Координация с клиентами и внутренними отделами...,Сопровождение проектов: координация с клиентам...
AT: Reports,NaN,Deliverable,?,?,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,Подготовка финальных отчётов для клиента: стру...,Составление отчетов для клиентов: проверка сод...
AT: Scientific research,not need (see AT: Commercialization),NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,Подготовка научных статей (вне IFСС и конферен...
AT: Sorting Logic,not need,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,"Разработка логики сортировки: анализ, встречи,..."
AT: TPC,not need,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Работа с данными: сбор, обработка, создание от..."
AT: Travel Support,NaN,Functional,Internal,Non-billable,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,same as earlier,"Организация получения загран.паспортов и виз, ..."
AT: Tutorship,NaN,Functional,Internal,Non-billable,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.0,Передача экспертных знаний о проекте/продукте ...,Наставничество и поддержка: передача экспертны...
AT: Validation,NaN,Stage,Client-oriented,billable,1.0,1,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Проверка итоговых материалов перед передачей к...,"Проверка корректности данных, расчётов, визуал..."
AT: Daily-Weekly,NaN,Functional,Internal,Non-billable,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Регулярные внутренние встречи команды или отде...,"Еженедельные встречи для подведения итогов, ан..."
Total number of tags assigned to the user,NaN,NaN,NaN,NaN,41.0,19,19.0,31.0,28.0,18.0,14.0,26.0,28.0,14.0,40.0,22.0,15.0,16.0,14.0,NaN,NaN,NaN

In [9]:
projects.rename(columns={'Old Name': 'Old name'}, inplace=True)

projects['Old name'] = projects['Comment'].str.extract(r'\((.*?)\)')
projects

In [10]:
projects.loc[projects['Old name'] != 0]

,Projects,Update Date,Comment,Old name
9,BC FR CHU BRDX: General,09.12.2025,0,BC Fr Bordeaux: General
10,BC FR CHU BRDX: Lab-Data,23.04.2026,0,BC Fr Bordeaux: Lab-Data
11,BC FR CHU BRDX: Tender Support,09.12.2025,0,BC Fr Bordeaux: Tender Support
12,BC Global: General,18.03.2026,0,BC GP: General
13,BC IRL Cork&Kerry: BI,01.07.2025,0,BC Cork&Kerry: BI
14,BC IRL Cork&Kerry: KPI Compliance,09.12.2025,0,BC Cork&Kerry: KPI Compliance
15,BC IRL Cork&Kerry: Lab-Avatar,01.07.2025,0,BC Cork&Kerry: Lab-Avatar
18,BC UK 6S: KPI Compliance,09.12.2025,0,BC 6S: KPI Compliance
19,BC UK MSC: Financial Tool,01.07.2025,0,BC MSC: Financial Tool
20,BC UK SWLP: BI,14.08.2025,0,BC SWLP: BI
21,BC UK SWLP: KPI Compliance,09.12.2025,0,BC SWLP: KPI Compliance
22,BC UK SWLP: Lab-Avatar,01.07.2025,0,BC SWLP: Lab-Avatar
23,BC UK SWLP: Transformation,01.07.2025,0,BC SWLP: Transformation
24,BC UK WoE: BI,01.07.2025,0,BC WoE: BI
25,BC UK WoE: KPI Compliance,09.12.2025,0,BC WoE: KPI Compliance

In [11]:
print(f'nt cols: {nt.columns}, np cols: {np.columns}, nc cols: {nc.columns}')

nt cols: Index(['id', 'workspace_id', 'name', 'at', 'creator_id', 'user'], dtype='object'), np cols: Index(['id', 'workspace_id', 'client_id', 'name', 'is_private', 'active', 'at',
       'created_at', 'server_deleted_at', 'color', 'billable', 'template',
       'auto_estimates', 'estimated_hours', 'estimated_seconds', 'rate',
       'rate_last_updated', 'currency', 'workspace_default_currency',
       'recurring', 'template_id', 'recurring_parameters', 'fixed_fee',
       'actual_hours', 'actual_seconds', 'total_count', 'client_name',
       'can_track_time', 'start_date', 'status', 'wid', 'cid', 'pinned',
       'user'],
      dtype='object'), nc cols: Index(['id', 'wid', 'archived', 'name', 'at', 'creator_id', 'total_count',
       'user'],
      dtype='object')

In [12]:
print(f'User specific tags - df cols: {df.columns}, tags_format cols: {tags_format.columns}, projects cols: {projects.columns}, clients cols: {clients.columns}')

User specific tags - df cols: Index(['New Name', 'Stages', 'Type 1', 'Type 2', 'ANAS', 'NIAL', 'SMVE',
       'AMAN', 'DIDA', 'AIVI', 'NIRO', 'VAEL', 'BODM', 'KAAN', 'KURO', 'CHAL',
       'BADA', 'LAOK', 'PRAR', 'TODA', 'New AT definition',
       'OLD AT definition'],
      dtype='object'), tags_format cols: Index(['Tags - Format', 'Update Date', 'Comment', 'Old name'], dtype='object'), projects cols: Index(['Projects', 'Update Date', 'Comment', 'Old name'], dtype='object'), clients cols: Index(['name', 'Update Date', 'Comment (old name)', 'Old name'], dtype='object')

import pandas as pd

# df_expected: индекс = tag, колонки = users, значения {0,1}
# nt: фактические данные, колонки ['id', 'workspace_id', 'name', 'at', 'creator_id', 'user']

def build_diff(df_expected: pd.DataFrame, nt: pd.DataFrame) -> pd.DataFrame:
    
    # --- 1. Expected: превращаем в long формат
    expected_long = (
        df_expected
        .reset_index()
        .melt(id_vars=df_expected.index.name or 'index',
              var_name='user',
              value_name='expected')
        .rename(columns={df_expected.index.name or 'index': 'tag'})
    )
    
    expected_long = expected_long[expected_long['expected'] == 1][['user', 'tag']]
    
    # --- 2. Actual: берем фактические теги
    actual = nt[['user', 'name']].rename(columns={'name': 'tag'}).drop_duplicates()
    
    # --- 3. ADD (не хватает)
    add_df = (
        expected_long
        .merge(actual, on=['user', 'tag'], how='left', indicator=True)
    )
    add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'tag']]
    add_df['doing'] = 'add'
    
    # --- 4. DELETE (лишние)
    delete_df = (
        actual
        .merge(expected_long, on=['user', 'tag'], how='left', indicator=True)
    )
    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'tag']]
    delete_df['doing'] = 'delete'
    
    # --- 5. Объединяем
    result = pd.concat([add_df, delete_df], ignore_index=True)
    
    # --- 6. Формируем финальный вид
    result = result.rename(columns={'tag': 'name'})
    result['right_variant'] = result['name']
    
    return result[['user', 'name', 'doing', 'right_variant']]

ddf = build_diff(df, nt)
ddf.loc[ddf.user == 'BADA']

import pandas as pd
import re

def normalize_tag(tag: str) -> str:
    if pd.isna(tag):
        return tag
    tag = tag.strip().lower()
    tag = re.sub(r'[-:]', '', tag)  # убираем - и :
    tag = re.sub(r'\s+', ' ', tag)  # нормализация пробелов
    return tag


def build_diff(df_expected: pd.DataFrame, nt: pd.DataFrame) -> pd.DataFrame:
    
    # --- 0. Expected -> long
    expected_long = (
        df_expected
        .reset_index()
        .melt(id_vars=df_expected.index.name or 'index',
              var_name='user',
              value_name='expected')
        .rename(columns={df_expected.index.name or 'index': 'tag'})
    )
    
    expected_long = expected_long[expected_long['expected'] == 1][['user', 'tag']]
    
    # --- 1. Actual
    actual = nt[['user', 'name']].rename(columns={'name': 'tag'}).drop_duplicates()

    print(actual.columns)
    
    # # --- 2. Фильтр Format:
    # actual = actual[~actual['tag'].str.startswith('Format:', na=False)]
    
    # --- 3. Нормализация
    expected_long['norm'] = expected_long['tag'].apply(normalize_tag)
    actual['norm'] = actual['tag'].apply(normalize_tag)
    
    # --- 4. REPLACE (ключевая часть)
    replace_df = (
        actual
        .merge(expected_long, on=['user', 'norm'], suffixes=('_actual', '_expected'))
    )
    
    replace_df = replace_df[
        replace_df['tag_actual'] != replace_df['tag_expected']
    ][['user', 'tag_actual', 'tag_expected']]
    
    replace_df = replace_df.rename(columns={
        'tag_actual': 'name',
        'tag_expected': 'right_variant'
    })
    replace_df['doing'] = 'replace'
    
    # --- 5. Убираем уже учтенные replace из выборок
    replace_keys = set(zip(replace_df['user'], replace_df['name']))
    
    actual_filtered = actual[
        ~actual.apply(lambda x: (x['user'], x['tag']) in replace_keys, axis=1)
    ]
    
    # --- 6. ADD
    add_df = (
        expected_long
        .merge(actual_filtered, on=['user', 'norm', 'tag'], how='left', indicator=True)
    )
    
    add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'tag']]
    add_df = add_df.rename(columns={'tag': 'name'})
    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']
    
    # --- 7. DELETE
    delete_df = (
        actual_filtered
        .merge(expected_long, on=['user', 'norm', 'tag'], how='left', indicator=True)
    )
    
    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'tag']]
    delete_df = delete_df.rename(columns={'tag': 'name'})
    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']
    
    # --- 8. Объединение
    result = pd.concat([add_df, delete_df, replace_df], ignore_index=True)
    
    return result[['user', 'name', 'doing', 'right_variant']]

In [13]:
tags_format

,Tags - Format,Update Date,Comment,Old name
0,Format: Individual work,01.07.2025,0,NaN
1,Format: Meeting Internal,01.07.2025,rename 08.06.2026 (Format: Internal meeting),Format: Internal meeting
2,Format: Meeting with Vendor,01.07.2025,0,NaN
3,Format: Meeting with Lab,01.07.2025,0,NaN
4,Format: Meeting with Hospital,09.12.2025,0,NaN

import pandas as pd
import re

def normalize_tag(tag: str) -> str:
    if pd.isna(tag):
        return tag
    tag = tag.strip().lower()
    tag = re.sub(r'[-:]', '', tag)  # убираем - и :
    tag = re.sub(r'\s+', ' ', tag)  # нормализация пробелов
    return tag


def build_tags_diff(df_expected: pd.DataFrame, nt: pd.DataFrame) -> pd.DataFrame:
    
    # --- 0. Expected -> long
    expected_long = (
        df_expected
        .reset_index()
        .melt(id_vars=df_expected.index.name or 'index',
              var_name='user',
              value_name='expected')
        .rename(columns={df_expected.index.name or 'index': 'tag'})
    )
    
    # --- фильтр expected
    expected_long = expected_long[expected_long['expected'] == 1][['user', 'tag']]
    
    # --- добавляем format в expected
    format_tags = tags_format[['Tags - Format']].rename(columns={'Tags - Format': 'tag'})
    
    
    users = expected_long[['user']].drop_duplicates()
    
    format_expanded_expected = users.merge(format_tags, how='cross')
    
    expected_long = pd.concat([expected_long, format_expanded_expected], ignore_index=True).drop_duplicates()
    
    # --- 1. Actual
    # --- 1. Actual (основные теги)
    # actual_main = nt[['user', 'name']].rename(columns={'name': 'tag'})
    if 'code' in nt.columns:
        nt['effective_tag'] = nt['code'].fillna(nt['name'])
    else:
        nt['effective_tag'] = nt['name']
    actual_main = nt[['user', 'effective_tag']].rename(columns={'effective_tag': 'tag'})
    
    # --- 1.1 Format теги (справочник)
    format_tags = tags_format[['Tags - Format']].rename(columns={'Tags - Format': 'tag'})
    
    # --- 1.2 Получаем всех пользователей
    users = actual_main[['user']].drop_duplicates()
    
    # --- 1.3 Декартово произведение: каждый user получает все format-теги
    format_expanded = users.merge(format_tags, how='cross')
    
    # --- 1.4 Объединение
    actual = pd.concat([actual_main, format_expanded], ignore_index=True).drop_duplicates()
    
    # --- 3. Нормализация
    expected_long['norm'] = expected_long['tag'].apply(normalize_tag)
    actual['norm'] = actual['tag'].apply(normalize_tag)
    
    # --- 4. REPLACE (ключевая часть)
    replace_df = (
        actual
        .merge(expected_long, on=['user', 'norm'], suffixes=('_actual', '_expected'))
    )
    
    replace_df = replace_df[
        replace_df['tag_actual'] != replace_df['tag_expected']
    ][['user', 'tag_actual', 'tag_expected']]
    
    replace_df = replace_df.rename(columns={
        'tag_actual': 'name',
        'tag_expected': 'right_variant'
    })
    replace_df['doing'] = 'replace'
    
    # --- 5. Убираем уже учтенные replace из выборок
    replace_keys = set(zip(replace_df['user'], replace_df['name']))
    
    actual_filtered = actual[
        ~actual.apply(lambda x: (x['user'], x['tag']) in replace_keys, axis=1)
    ]
    
    # --- 6. ADD
    add_df = (
        expected_long
        .merge(actual_filtered, on=['user', 'norm', 'tag'], how='left', indicator=True)
    )
    
    add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'tag']]
    add_df = add_df.rename(columns={'tag': 'name'})
    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']
    
    # --- 7. DELETE
    delete_df = (
        actual_filtered
        .merge(expected_long, on=['user', 'norm', 'tag'], how='left', indicator=True)
    )
    
    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'tag']]
    delete_df = delete_df.rename(columns={'tag': 'name'})
    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']
    
    # --- 8. Объединение
    result = pd.concat([add_df, delete_df, replace_df], ignore_index=True)
    
    return result[['user', 'name', 'doing', 'right_variant']]

In [14]:
import pandas as pd
import re


def normalize_tag(tag: str) -> str:
    if pd.isna(tag):
        return tag
    tag = tag.strip().lower()
    tag = re.sub(r'[-:]', '', tag)
    tag = re.sub(r'\s+', ' ', tag)
    return tag


def build_tags_diff(df_expected: pd.DataFrame, nt: pd.DataFrame) -> pd.DataFrame:

    # --------------------------------------------------
    # Expected -> long
    # --------------------------------------------------
    expected_long = (
        df_expected
        .reset_index()
        .melt(
            id_vars=df_expected.index.name or 'index',
            var_name='user',
            value_name='expected'
        )
        .rename(columns={
            df_expected.index.name or 'index': 'tag'
        })
    )

    expected_long = expected_long[
        expected_long['expected'] == 1
    ][['user', 'tag']]

    # --------------------------------------------------
    # Добавляем format tags в expected
    # --------------------------------------------------
    format_tags = tags_format[['Tags - Format']].rename(
        columns={'Tags - Format': 'tag'}
    )

    users = expected_long[['user']].drop_duplicates()

    format_expanded_expected = users.merge(
        format_tags,
        how='cross'
    )

    expected_long = pd.concat(
        [expected_long, format_expanded_expected],
        ignore_index=True
    ).drop_duplicates()

    # --------------------------------------------------
    # Actual
    # --------------------------------------------------
    nt = nt.copy()

    if 'code' in nt.columns:
        nt['effective_tag'] = nt['code'].fillna(nt['name'])
    else:
        nt['effective_tag'] = nt['name']

    actual_main = nt[['user', 'effective_tag']].rename(
        columns={'effective_tag': 'tag'}
    )

    # --------------------------------------------------
    # Добавляем format tags в actual
    # --------------------------------------------------
    format_tags = tags_format[['Tags - Format']].rename(
        columns={'Tags - Format': 'tag'}
    )

    users = actual_main[['user']].drop_duplicates()

    format_expanded = users.merge(
        format_tags,
        how='cross'
    )

    actual = pd.concat(
        [actual_main, format_expanded],
        ignore_index=True
    ).drop_duplicates()

    # --------------------------------------------------
    # Нормализация
    # --------------------------------------------------
    expected_long['norm'] = expected_long['tag'].apply(normalize_tag)
    actual['norm'] = actual['tag'].apply(normalize_tag)

    # --------------------------------------------------
    # REPLACE №1 (через нормализацию)
    # --------------------------------------------------
    replace_df = (
        actual
        .merge(
            expected_long,
            on=['user', 'norm'],
            suffixes=('_actual', '_expected')
        )
    )

    replace_df = replace_df[
        replace_df['tag_actual'] != replace_df['tag_expected']
    ][['user', 'tag_actual', 'tag_expected']]

    replace_df = replace_df.rename(
        columns={
            'tag_actual': 'name',
            'tag_expected': 'right_variant'
        }
    )

    replace_df['doing'] = 'replace'

    # --------------------------------------------------
    # REPLACE №2 (через Old name)
    # --------------------------------------------------
    rename_map = (
        tags_format[
            tags_format['Old name'].notna()
        ][['Tags - Format', 'Old name']]
        .rename(
            columns={
                'Tags - Format': 'new_name',
                'Old name': 'old_name'
            }
        )
    )

    if not rename_map.empty:

        rename_map['old_norm'] = rename_map['old_name'].apply(
            normalize_tag
        )

        rename_df = (
            actual
            .merge(
                rename_map,
                left_on='norm',
                right_on='old_norm',
                how='inner'
            )
        )

        rename_df = rename_df[
            ['user', 'tag', 'new_name']
        ].rename(
            columns={
                'tag': 'name',
                'new_name': 'right_variant'
            }
        )

        rename_df['doing'] = 'replace'

        replace_df = pd.concat(
            [replace_df, rename_df],
            ignore_index=True
        )

    replace_df = replace_df.drop_duplicates()

    # --------------------------------------------------
    # Исключаем replace из дальнейшего анализа
    # --------------------------------------------------
    replace_keys = set(
        zip(
            replace_df['user'],
            replace_df['name']
        )
    )

    actual_filtered = actual[
        ~actual.apply(
            lambda x: (x['user'], x['tag']) in replace_keys,
            axis=1
        )
    ]

    # --------------------------------------------------
    # ADD
    # --------------------------------------------------
    add_df = (
        expected_long
        .merge(
            actual_filtered,
            on=['user', 'norm', 'tag'],
            how='left',
            indicator=True
        )
    )

    add_df = add_df[
        add_df['_merge'] == 'left_only'
    ][['user', 'tag']]

    add_df = add_df.rename(
        columns={'tag': 'name'}
    )

    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']

    # --------------------------------------------------
    # DELETE
    # --------------------------------------------------
    delete_df = (
        actual_filtered
        .merge(
            expected_long,
            on=['user', 'norm', 'tag'],
            how='left',
            indicator=True
        )
    )

    delete_df = delete_df[
        delete_df['_merge'] == 'left_only'
    ][['user', 'tag']]

    delete_df = delete_df.rename(
        columns={'tag': 'name'}
    )

    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']

    # --------------------------------------------------
    # RESULT
    # --------------------------------------------------
    result = pd.concat(
        [add_df, delete_df, replace_df],
        ignore_index=True
    )

    return result[
        ['user', 'name', 'doing', 'right_variant']
    ].drop_duplicates()

ok_tags = [
"AT: Assessment on site",
"AT: Bank operations",
"AT: Business requirements",
"AT: Travel",
"AT: Calculations and visualizat",
"AT: RRL/Cito List",
"AT: Client's data handling",
"AT: Marketing",
"AT: Commercial",
"AT: Contract Heatmap",
"AT: Data&Systems",
"AT: Data Research",
"AT: Demo",
"AT: Design",
"AT: Education",
"AT: HR management",
"AT: HR recruiting",
"AT: Onboarding",
"AT: Internal Admin",
"AT: Financial Admin",
"AT: Invoicing",
"AT: Lab-Data ARAB",
"AT: Lab-Data Matching",
"AT: Lab-Data Technical Charts",
"AT: Horizontal File",
"AT: Local-Catalog",
"AT: Make-up",
"AT: Methodology",
"AT: N/A",
"AT: Office maintenance",
"AT: Team-Events",
"AT: Presentations",
"AT: Project-Management",
"AT: Reports",
"AT: Travel Support",
"AT: Tutorship",
"AT: Validation",
"AT: Daily-Weekly",
"AT: Matterport",
"AT: Lab-Data Dictionaries",
]

old_tags_to_delete = nt.loc[(nt.user.isin(['ANAS', 'SMVE'])) & ~(nt.name.isin(ok_tags)), ['user', 'name']]
old_tags_to_delete['doing'] = 'delete'
old_tags_to_delete['right_variant'] = old_tags_to_delete['name']
old_tags_to_delete

In [15]:
nt

,id,workspace_id,name,at,creator_id,user
0,20753825,8752160,AT: Assessment on site,2026-08-04T20:04:51.020348Z,11312038,BADA
1,20753860,8752160,AT: Business requirements,2026-08-04T20:04:51.885916Z,11312038,BADA
2,18510939,8752160,AT: Calculations and visualization,2025-12-12T13:39:49.068556Z,11312038,BADA
3,20754104,8752160,AT: Client's data handling,2026-08-04T21:05:53.083619Z,11312038,BADA
4,20753583,8752160,AT: Coding,2026-08-04T20:04:46.780936Z,11312038,BADA
...,...,...,...,...,...,...
793,20853965,21648145,F: Individual work,2026-09-03T11:12:18.57087Z,13421576,GOBE
794,20853348,21648145,F: Meeting Internal,2026-09-03T08:23:21.398996Z,13421576,GOBE
795,20853966,21648145,F: Meeting with Hospital,2026-09-03T11:12:19.326788Z,13421576,GOBE
796,20853967,21648145,F: Meeting with Lab,2026-09-03T11:12:19.86711Z,13421576,GOBE
797,20853968,21648145,F: Meeting with Vendor,2026-09-03T11:12:20.440292Z,13421576,GOBE

In [16]:
tags_diff = build_tags_diff(df, nt)
# tags_diff.loc[tags_diff.user == 'CHAL', 'name'].unique()
tags_diff

,user,name,doing,right_variant
0,ANAS,AT: Business trip,add,AT: Business trip
1,ANAS,AT: Cito List,add,AT: Cito List
2,ANAS,AT: Commercialization,add,AT: Commercialization
3,ANAS,AT: Contract,add,AT: Contract
4,ANAS,AT: Internal reports,add,AT: Internal reports
...,...,...,...,...
651,GOBE,Format: Individual work,delete,Format: Individual work
652,GOBE,Format: Meeting Internal,delete,Format: Meeting Internal
653,GOBE,Format: Meeting with Vendor,delete,Format: Meeting with Vendor
654,GOBE,Format: Meeting with Lab,delete,Format: Meeting with Lab
655,GOBE,Format: Meeting with Hospital,delete,Format: Meeting with Hospital

In [17]:
tags_diff['name'].unique()

array(['AT: Business trip', 'AT: Cito List', 'AT: Commercialization',
       'AT: Contract', 'AT: Internal reports',
       'AT: Lab-Efficiency-Workshop', 'AT: Lab-Flow',
       'AT: Lab-Horizontals', 'AT: Lab-Modeling', 'AT: ML', 'AT: Presale',
       'AT: Scientific research', 'AT: Methodology', 'AT: Validation',
       'AT: Invoicing', 'AT: Office maintenance',
       'AT: Business requirements', 'AT: Reports', 'AT: Travel Support',
       'AT: Assessment on site', "AT: Client's data handling",
       'AT: Coding', 'AT: Commercial', 'AT: Communication with Suppliers',
       'AT: Contract Heatmap', 'AT: Demo', 'AT: Design', 'AT: Education',
       'AT: Horizontal File', 'AT: HR management', 'AT: HR recruiting',
       'AT: Lab-Data Dictionaries', 'AT: Lab-Data Technical Charts',
       'AT: Lab-Efficiency', 'AT: Local-Catalog', 'AT: Make-up',
       'AT: Marketing', 'AT: Matterport', 'AT: Onboarding',
       'AT: Product Delivery', 'AT: Project-Management', 'AT: Release',
       'AT: Retrospective', 'AT: RRL/Cito List', 'AT: Sprint Planning',
       'AT: Support', 'AT: Team-Events', 'AT: Testing', 'AT: Travel',
       'AT: Tutorship', 'F: Individual work', 'F: Meeting Internal',
       'F: Meeting with Hospital', 'F: Meeting with Lab',
       'F: Meeting with Vendor', 'AT: Calculations and visualization',
       'AT: Sorting Logic', 'AT: Data&Systems', 'AT: Lab-Data ARAB',
       'AT: Lab-Data Matching',
       'CAT: 1 |  Исследование разрозненных источников данных в клиентских информационных системах',
       'CAT: 2 | Планирование сбора данных в хранилище (наладка ETL совместно с системными инженерами)',
       'CAT: 3 | Оценка чистоты данных, участие в разработке правил такой оценки',
       'CAT: 4 | Разработка и доработка BI-отчетов и дашбордов',
       'CAT: 5 | Разработка рабочих прототипов программных продуктов (Minimum Viable Product, далее - MVP)',
       'CAT: 6 | Поддержка отдела информационных технологий Заказчика в рамках преобразования MVP',
       'CAT: 7 | Услуги по аналитике данных в рамках консалтинговых проектов Заказчика',
       'CAT: 8 | Дополнителные выплаты', 'AT: Financial Admin',
       'AT: Presentations', 'AT: Bank operations', 'AT: Data Research',
       'Dep: Consulting', 'АТ: Marketing', 'AT: Daily-Weekly',
       'AT: Internal Admin', 'AT: N/A', 'Format: Individual work',
       'Format: Meeting Internal', 'Format: Meeting with Vendor',
       'Format: Meeting with Lab', 'Format: Meeting with Hospital'],
      dtype=object)

In [18]:
exception_list = ['CAT: 1 |  Исследование разрозненных источников данных в клиентских информационных системах',
                   'CAT: 2 | Планирование сбора данных в хранилище (наладка ETL совместно с системными инженерами)',
                   'CAT: 3 | Оценка чистоты данных, участие в разработке правил такой оценки',
                   'CAT: 4 | Разработка и доработка BI-отчетов и дашбордов',
                   'CAT: 5 | Разработка рабочих прототипов программных продуктов (Minimum Viable Product, далее - MVP)',
                   'CAT: 6 | Поддержка отдела информационных технологий Заказчика в рамках преобразования MVP',
                   'CAT: 7 | Услуги по аналитике данных в рамках консалтинговых проектов Заказчика',
                   'CAT: 8 | Дополнителные выплаты',
                 ]
exception_personal = {
    'SMVE': 'Dep: Consulting'
}

tags_diff.drop(tags_diff[(tags_diff.name.isin(exception_list)) & (tags_diff.user=='CHAL')].index, axis=0, inplace=True)
tags_diff.drop(tags_diff[(tags_diff.name=='Dep: Consulting') & (tags_diff.user=='SMVE')].index, axis=0, inplace=True)
tags_diff

,user,name,doing,right_variant
0,ANAS,AT: Business trip,add,AT: Business trip
1,ANAS,AT: Cito List,add,AT: Cito List
2,ANAS,AT: Commercialization,add,AT: Commercialization
3,ANAS,AT: Contract,add,AT: Contract
4,ANAS,AT: Internal reports,add,AT: Internal reports
...,...,...,...,...
651,GOBE,Format: Individual work,delete,Format: Individual work
652,GOBE,Format: Meeting Internal,delete,Format: Meeting Internal
653,GOBE,Format: Meeting with Vendor,delete,Format: Meeting with Vendor
654,GOBE,Format: Meeting with Lab,delete,Format: Meeting with Lab
655,GOBE,Format: Meeting with Hospital,delete,Format: Meeting with Hospital

# Dep: Consulting - нужно (подумать подобный себе)

In [19]:
tags_format

,Tags - Format,Update Date,Comment,Old name
0,Format: Individual work,01.07.2025,0,NaN
1,Format: Meeting Internal,01.07.2025,rename 08.06.2026 (Format: Internal meeting),Format: Internal meeting
2,Format: Meeting with Vendor,01.07.2025,0,NaN
3,Format: Meeting with Lab,01.07.2025,0,NaN
4,Format: Meeting with Hospital,09.12.2025,0,NaN

In [20]:
projects

                        Projects Update Date Comment Old name
0             Abbott: Sorters BI  01.07.2025       0        0
1            Alrijne: Assessment  30.09.2025       0        0
2               Alrijne: General  09.12.2025       0        0
3   Alrijne: Hospital Lab-Design  09.12.2025       0        0
4            Alrijne: Lab-Avatar  01.07.2025       0        0
..                           ...         ...     ...      ...
73         StreekLab: Lab-Avatar  01.07.2025       0        0
74     StreekLab: Lab-Calculator  01.07.2025       0        0
75           StreekLab: Lab-Data  01.07.2025       0        0
76     StreekLab: Tender Support  01.07.2025       0        0
77     StreekLab: Transformation  01.07.2025       0        0

[78 rows x 4 columns]

In [21]:
clients

,name,Update Date,Comment (old name),Old name
0,Abbott,01.07.2025,0,NaN
1,Alrijne,01.07.2025,0,NaN
2,BC Europe&UK,09.12.2025,0,NaN
3,BC FR CHU BRDX,09.12.2025,rename 26.05.2026 (BC Fr Bordeaux),BC Fr Bordeaux
4,BC Global,18.03.2026,rename 26.05.2026 (BC GP),BC GP
5,BC IRL Cork&Kerry,01.07.2025,rename 26.05.2026 (BC Cork&Kerry),BC Cork&Kerry
6,BC IRL NWT,26.05.2026,need to add (new),new
7,BC UK 6S,09.12.2025,rename 26.05.2026 (BC 6S),BC 6S
8,BC UK MSC,01.07.2025,rename 26.05.2026 (BC MSC),BC MSC
9,BC UK SWLP,01.07.2025,rename 26.05.2026 (BC SWLP),BC SWLP
10,BC UK WoE,01.07.2025,rename 26.05.2026 (BC WoE),BC WoE
11,Certe,01.07.2025,0,NaN
12,Dicoon,09.12.2025,0,NaN
13,GCG,01.07.2025,0,NaN
14,Labexa,01.07.2025,0,NaN
15,Potential Client,01.10.2025,0,NaN
16,Regiolab,09.12.2025,0,NaN
17,Siemens-Bernhoven,01.07.2025,0,NaN
18,StreekLab,01.07.2025,0,NaN

import pandas as pd
import re

def normalize_tag(tag: str) -> str:
    if pd.isna(tag):
        return tag
    tag = tag.strip().lower()
    tag = re.sub(r'[-:]', '', tag)
    tag = re.sub(r'\s+', ' ', tag)
    return tag


def build_diff_entities(df_expected: pd.DataFrame, actual_df: pd.DataFrame, entity: str) -> pd.DataFrame:
    """
    entity: 'projects' или 'clients'
    """

    # --- 1. Определяем колонки
    if entity == 'projects':
        expected_col = 'Projects'
        actual_col = 'name'
    elif entity == 'clients':
        expected_col = 'Client Name'
        actual_col = 'name'
    else:
        raise ValueError("entity must be 'projects' or 'clients'")

    # --- 2. Expected
    expected = (
        df_expected[[expected_col]]
        .rename(columns={expected_col: 'name'})
        .dropna()
        .drop_duplicates()
    )

    expected['norm'] = expected['name'].apply(normalize_tag)

    # --- 3. Actual
    # actual = (
    #     actual_df[['user', actual_col]]
    #     .rename(columns={actual_col: 'name'})
    #     .dropna()
    #     .drop_duplicates()
    # )

    # actual['norm'] = actual['name'].apply(normalize_tag)

    # --- 3. Actual
    if 'code' in actual_df.columns:
        actual = (
            actual_df[['user', actual_col, 'code']]
            .rename(columns={actual_col: 'name'})
            .dropna(subset=['user'])
            .drop_duplicates()
        )
    
        # code приоритетнее name
        actual['name'] = actual['code'].fillna(actual['name'])
    else:
        actual = (
            actual_df[['user', actual_col]]
            .rename(columns={actual_col: 'name'})
            .dropna()
            .drop_duplicates()
        )
    
    actual['norm'] = actual['name'].apply(normalize_tag)

    # --- 4. REPLACE
    replace_df = (
        actual
        .merge(expected, on='norm', suffixes=('_actual', '_expected'))
    )

    replace_df = replace_df[
        replace_df['name_actual'] != replace_df['name_expected']
    ][['user', 'name_actual', 'name_expected']]

    replace_df = replace_df.rename(columns={
        'name_actual': 'name',
        'name_expected': 'right_variant'
    })

    replace_df['doing'] = 'replace'

    # --- 5. Убираем replace из дальнейших расчетов (по norm!)
    replace_keys = set(zip(replace_df['user'], replace_df['name'].apply(normalize_tag)))

    actual_filtered = actual[
        ~actual.apply(lambda x: (x['user'], x['norm']) in replace_keys, axis=1)
    ]

    # # --- 6. ADD (expected нет в actual)
    # add_df = (
    #     expected
    #     .merge(actual_filtered[['norm']].drop_duplicates(), on='norm', how='left', indicator=True)
    # )

    # add_df = add_df[add_df['_merge'] == 'left_only'][['name']]
    # add_df['doing'] = 'add'
    # add_df['right_variant'] = add_df['name']
    # add_df['user'] = None

    # --- 6. ADD (user-level!)
    users = actual[['user']].drop_duplicates()
    
    expected_expanded = users.merge(expected[['name', 'norm']], how='cross')
    
    add_df = (
        expected_expanded
        .merge(actual_filtered[['user', 'norm']], on=['user', 'norm'], how='left', indicator=True)
    )
    
    add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'name']]
    
    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']

    # --- 7. DELETE (actual нет в expected)
    delete_df = (
        actual_filtered
        .merge(expected[['norm']], on='norm', how='left', indicator=True)
    )

    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'name']]
    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']

    # --- 8. Объединение
    result = pd.concat([add_df, delete_df, replace_df], ignore_index=True)

    return result[['user', 'name', 'doing', 'right_variant']]

def build_diff_entities(df_expected: pd.DataFrame, actual_df: pd.DataFrame, entity: str) -> pd.DataFrame:
    # --- 1. Определяем колонки
    if entity == 'projects':
        expected_col = 'Projects'
        actual_col = 'name'
    elif entity == 'clients':
        # expected_col = 'Client Name'
        expected_col = 'name'
        actual_col = 'name'
    else:
        raise ValueError("entity must be 'projects' or 'clients'")

    # --- 2. Expected
    has_code = 'Old name' in df_expected.columns

    expected = (
        df_expected[[expected_col] + (['Old name'] if has_code else [])]
        .rename(columns={expected_col: 'name'})
        .dropna(subset=['name'])
        .drop_duplicates()
    )
    expected['norm'] = expected['name'].apply(normalize_tag)

    # code — старое имя в actual, которое надо переименовать в name
    if has_code:
        code_map = (
            expected[expected['Old name'].notna() & (expected['Old name'] != 0)]
            [['name', 'Old name']]
            .copy()
        )
        # norm старого имени → новое имя
        code_map['old_norm'] = code_map['Old name'].apply(normalize_tag)
    else:
        code_map = pd.DataFrame(columns=['name', 'Old name', 'old_norm'])

    # --- 3. Actual
    actual = (
        actual_df[['user', actual_col]]
        .rename(columns={actual_col: 'name'})
        .dropna()
        .drop_duplicates()
    )
    actual['norm'] = actual['name'].apply(normalize_tag)

    # --- 4. REPLACE через code (старое имя в actual → новое из expected)
    code_replace_df = pd.DataFrame()
    if not code_map.empty:
        code_replace_df = (
            actual
            .merge(code_map[['name', 'old_norm']], left_on='norm', right_on='old_norm')
            .rename(columns={'name_x': 'name', 'name_y': 'right_variant'})
            [['user', 'name', 'right_variant']]
        )
        code_replace_df['doing'] = 'replace'

    # --- 5. REPLACE через нормализацию (имя отличается, но norm совпадает)
    norm_replace_df = (
        actual
        .merge(expected[['name', 'norm']], on='norm', suffixes=('_actual', '_expected'))
    )
    norm_replace_df = norm_replace_df[
        norm_replace_df['name_actual'] != norm_replace_df['name_expected']
    ][['user', 'name_actual', 'name_expected']]
    norm_replace_df = norm_replace_df.rename(columns={
        'name_actual': 'name',
        'name_expected': 'right_variant'
    })
    norm_replace_df['doing'] = 'replace'

    replace_df = pd.concat([code_replace_df, norm_replace_df], ignore_index=True)

    # --- 6. Убираем replace из дальнейших расчетов
    replace_keys = set(zip(replace_df['user'], replace_df['name'].apply(normalize_tag)))
    actual_filtered = actual[
        ~actual.apply(lambda x: (x['user'], x['norm']) in replace_keys, axis=1)
    ]

    # Из expected убираем те name, для которых уже есть code-replace
    # (чтобы они не попали в ADD)
    code_replaced_new_norms = set(code_map['name'].apply(normalize_tag)) if not code_map.empty else set()
    expected_for_add = expected[~expected['norm'].isin(code_replaced_new_norms)]

    # --- 7. ADD (user-level)
    # users = actual[['user']].drop_duplicates()
    # expected_expanded = users.merge(expected_for_add[['name', 'norm']], how='cross')

    # add_df = (
    #     expected_expanded
    #     .merge(actual_filtered[['user', 'norm']], on=['user', 'norm'], how='left', indicator=True)
    # )
    # add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'name']]
    # add_df['doing'] = 'add'
    # add_df['right_variant'] = add_df['name']

    # --- 7. ADD (user-level)
    users = actual[['user']].drop_duplicates()
    expected_expanded = users.merge(expected[['name', 'norm']], how='cross')

    # Уже покрытые через code-replace: (user, new_norm) — не добавляем
    code_replace_keys = (
        set(zip(code_replace_df['user'], code_replace_df['right_variant'].apply(normalize_tag)))
        if not code_replace_df.empty else set()
    )

    add_df = (
        expected_expanded
        .merge(actual_filtered[['user', 'norm']], on=['user', 'norm'], how='left', indicator=True)
    )
    
    # Явно задаём колонки чтобы не словить KeyError на пустом датафрейме
    add_df = add_df[add_df['_merge'] == 'left_only'].reindex(columns=['user', 'name', 'norm'])

    # Убираем только те (user, norm), которые уже закрыты через code-replace
    if not add_df.empty and code_replace_keys:
        add_df = add_df[
            ~add_df.apply(lambda x: (x['user'], x['norm']) in code_replace_keys, axis=1)
        ]

    add_df = add_df[['user', 'name']]
    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']

    # --- 8. DELETE (actual нет в expected, и не участвует в code-replace как старое имя)
    code_old_norms = set(code_map['old_norm']) if not code_map.empty else set()
    actual_for_delete = actual_filtered[~actual_filtered['norm'].isin(code_old_norms)]

    delete_df = (
        actual_for_delete
        .merge(expected[['norm']], on='norm', how='left', indicator=True)
    )
    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'name']]
    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']

    # --- 9. Объединение
    result = pd.concat([add_df, delete_df, replace_df], ignore_index=True)
    return result[['user', 'name', 'doing', 'right_variant']]

In [22]:
def build_diff_entities(df_expected: pd.DataFrame, actual_df: pd.DataFrame, entity: str) -> pd.DataFrame:
    # --- 1. Определяем колонки
    if entity == 'projects':
        expected_col = 'Projects'
        actual_col = 'name'
    elif entity == 'clients':
        # expected_col = 'Client Name'
        expected_col = 'name'
        actual_col = 'name'
    else:
        raise ValueError("entity must be 'projects' or 'clients'")

    # --- 2. Expected
    has_code = 'Old name' in df_expected.columns

    expected = (
        df_expected[[expected_col] + (['Old name'] if has_code else [])]
        .rename(columns={expected_col: 'name'})
        .dropna(subset=['name'])
        .drop_duplicates()
    )
    expected['norm'] = expected['name'].apply(normalize_tag)

    # code — старое имя в actual, которое надо переименовать в name
    if has_code:
        code_map = (
            expected[expected['Old name'].notna() & (expected['Old name'] != 0)]
            [['name', 'Old name']]
            .copy()
        )
        # norm старого имени → новое имя
        code_map['old_norm'] = code_map['Old name'].apply(normalize_tag)
    else:
        code_map = pd.DataFrame(columns=['name', 'Old name', 'old_norm'])

    # --- 3. Actual
    actual = (
        actual_df[['user', actual_col]]
        .rename(columns={actual_col: 'name'})
        .dropna()
        .drop_duplicates()
    )
    actual['norm'] = actual['name'].apply(normalize_tag)

    # --- 4. REPLACE через code (старое имя в actual → новое из expected)
    code_replace_df = pd.DataFrame()
    if not code_map.empty:
        code_replace_df = (
            actual
            .merge(code_map[['name', 'old_norm']], left_on='norm', right_on='old_norm')
            .rename(columns={'name_x': 'name', 'name_y': 'right_variant'})
            [['user', 'name', 'right_variant']]
        )
        code_replace_df['doing'] = 'replace'

    # --- 5. REPLACE через нормализацию (имя отличается, но norm совпадает)
    norm_replace_df = (
        actual
        .merge(expected[['name', 'norm']], on='norm', suffixes=('_actual', '_expected'))
    )
    norm_replace_df = norm_replace_df[
        norm_replace_df['name_actual'] != norm_replace_df['name_expected']
    ][['user', 'name_actual', 'name_expected']]
    norm_replace_df = norm_replace_df.rename(columns={
        'name_actual': 'name',
        'name_expected': 'right_variant'
    })
    norm_replace_df['doing'] = 'replace'

    replace_df = pd.concat([code_replace_df, norm_replace_df], ignore_index=True)

    # --- 6. Убираем replace из дальнейших расчетов
    replace_keys = set(zip(replace_df['user'], replace_df['name'].apply(normalize_tag)))
    actual_filtered = actual[
        ~actual.apply(lambda x: (x['user'], x['norm']) in replace_keys, axis=1)
    ]

    # --- 7. ADD (user-level)
    users = actual[['user']].drop_duplicates()
    expected_expanded = users.merge(expected[['name', 'norm']], how='cross')

    # Для проверки ADD: actual_filtered + новые имена из code-replace (они уже "есть" у юзера)
    code_replace_as_actual = pd.DataFrame()
    if not code_replace_df.empty:
        code_replace_as_actual = code_replace_df[['user', 'right_variant']].copy()
        code_replace_as_actual['norm'] = code_replace_as_actual['right_variant'].apply(normalize_tag)
        code_replace_as_actual = code_replace_as_actual[['user', 'norm']]

    actual_for_add = pd.concat(
        [actual_filtered[['user', 'norm']], code_replace_as_actual],
        ignore_index=True
    ).drop_duplicates()

    add_df = (
        expected_expanded
        .merge(actual_for_add[['user', 'norm']], on=['user', 'norm'], how='left', indicator=True)
    )
    add_df = add_df[add_df['_merge'] == 'left_only'][['user', 'name']]
    add_df['doing'] = 'add'
    add_df['right_variant'] = add_df['name']


    # --- 8. DELETE (actual нет в expected, и не участвует в code-replace как старое имя)
    code_old_norms = set(code_map['old_norm']) if not code_map.empty else set()
    actual_for_delete = actual_filtered[~actual_filtered['norm'].isin(code_old_norms)]

    delete_df = (
        actual_for_delete
        .merge(expected[['norm']], on='norm', how='left', indicator=True)
    )
    delete_df = delete_df[delete_df['_merge'] == 'left_only'][['user', 'name']]
    delete_df['doing'] = 'delete'
    delete_df['right_variant'] = delete_df['name']

    # --- 9. Объединение
    result = pd.concat([add_df, delete_df, replace_df], ignore_index=True)
    return result[['user', 'name', 'doing', 'right_variant']]

In [23]:
np

,id,workspace_id,client_id,name,is_private,active,at,created_at,server_deleted_at,color,billable,template,auto_estimates,estimated_hours,estimated_seconds,rate,rate_last_updated,currency,workspace_default_currency,recurring,template_id,recurring_parameters,fixed_fee,actual_hours,actual_seconds,total_count,client_name,can_track_time,start_date,status,wid,cid,pinned,user
0,212212076,8752160,67586844,Abbott: Sorters BI,True,True,2025-12-12T23:26:46+00:00,2025-06-29T22:32:51+00:00,NaN,#0b83d9,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,69,Abbott,True,2025-06-29,active,8752160,67586844,False,BADA
1,214227472,8752160,67586845,Alrijne: Assessment,True,True,2025-12-12T23:26:46+00:00,2025-09-30T17:14:58+00:00,NaN,#0b83d9,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,69,Alrijne,True,2025-09-30,active,8752160,67586845,False,BADA
2,215582682,8752160,67586845,Alrijne: General,True,True,2025-12-12T23:26:46+00:00,2025-12-09T13:39:25+00:00,NaN,#0b83d9,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,69,Alrijne,True,2025-12-09,active,8752160,67586845,False,BADA
3,215582683,8752160,67586845,Alrijne: Hospital Lab-Design,True,True,2025-12-12T23:26:46+00:00,2025-12-09T13:39:26+00:00,NaN,#0b83d9,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,69,Alrijne,True,2025-12-09,active,8752160,67586845,False,BADA
4,212212077,8752160,67586845,Alrijne: Lab-Avatar,True,True,2025-12-12T23:26:47+00:00,2025-06-29T22:32:52+00:00,NaN,#0b83d9,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,69,Alrijne,True,2025-06-29,active,8752160,67586845,False,BADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,222216360,21648145,69129583,Regiolab: Lab-Academy,True,True,2026-09-03T10:08:00+00:00,2026-09-03T10:08:00+00:00,NaN,#0b83d9,True,0.0,0.0,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,9,Regiolab,True,2026-09-03,active,21648145,69129583,False,GOBE
1111,222216361,21648145,69129583,Regiolab: Lab-Avatar,True,True,2026-09-03T10:08:00+00:00,2026-09-03T10:08:00+00:00,NaN,#0b83d9,True,0.0,0.0,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,9,Regiolab,True,2026-09-03,active,21648145,69129583,False,GOBE
1112,222216363,21648145,69129583,Regiolab: Lab-Calculator,True,True,2026-09-03T10:08:01+00:00,2026-09-03T10:08:01+00:00,NaN,#0b83d9,True,0.0,0.0,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,9,Regiolab,True,2026-09-03,active,21648145,69129583,False,GOBE
1113,222216365,21648145,69129583,Regiolab: Lab-Data,True,True,2026-09-03T10:08:01+00:00,2026-09-03T10:08:01+00:00,NaN,#0b83d9,True,0.0,0.0,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,9,Regiolab,True,2026-09-03,active,21648145,69129583,False,GOBE
1114,222216367,21648145,69129583,Regiolab: UPC,True,True,2026-09-03T10:08:02+00:00,2026-09-03T10:08:02+00:00,NaN,#0b83d9,True,0.0,0.0,NaN,NaN,NaN,NaN,NaN,USD,False,NaN,NaN,NaN,NaN,NaN,9,Regiolab,True,2026-09-03,active,21648145,69129583,False,GOBE

In [24]:
projects.loc[projects['Old name'] != 0]

,Projects,Update Date,Comment,Old name
9,BC FR CHU BRDX: General,09.12.2025,0,BC Fr Bordeaux: General
10,BC FR CHU BRDX: Lab-Data,23.04.2026,0,BC Fr Bordeaux: Lab-Data
11,BC FR CHU BRDX: Tender Support,09.12.2025,0,BC Fr Bordeaux: Tender Support
12,BC Global: General,18.03.2026,0,BC GP: General
13,BC IRL Cork&Kerry: BI,01.07.2025,0,BC Cork&Kerry: BI
14,BC IRL Cork&Kerry: KPI Compliance,09.12.2025,0,BC Cork&Kerry: KPI Compliance
15,BC IRL Cork&Kerry: Lab-Avatar,01.07.2025,0,BC Cork&Kerry: Lab-Avatar
18,BC UK 6S: KPI Compliance,09.12.2025,0,BC 6S: KPI Compliance
19,BC UK MSC: Financial Tool,01.07.2025,0,BC MSC: Financial Tool
20,BC UK SWLP: BI,14.08.2025,0,BC SWLP: BI
21,BC UK SWLP: KPI Compliance,09.12.2025,0,BC SWLP: KPI Compliance
22,BC UK SWLP: Lab-Avatar,01.07.2025,0,BC SWLP: Lab-Avatar
23,BC UK SWLP: Transformation,01.07.2025,0,BC SWLP: Transformation
24,BC UK WoE: BI,01.07.2025,0,BC WoE: BI
25,BC UK WoE: KPI Compliance,09.12.2025,0,BC WoE: KPI Compliance

In [25]:
projects_diff = build_diff_entities(projects, np, 'projects')
projects_diff = projects_diff.loc[(projects_diff.name != 'GCG: GC AG') & (projects_diff.name != 'GCG: More Life')]
projects_diff.loc[projects_diff.user=='BADA']
projects_diff

,user,name,doing,right_variant
0,BADA,BC IRL Cork&Kerry: KPI Compliance,add,BC IRL Cork&Kerry: KPI Compliance
1,BADA,BC UK 6S: KPI Compliance,add,BC UK 6S: KPI Compliance
2,BADA,BC UK SWLP: KPI Compliance,add,BC UK SWLP: KPI Compliance
3,BADA,BC UK WoE: KPI Compliance,add,BC UK WoE: KPI Compliance
4,BADA,Certe: BI,add,Certe: BI
...,...,...,...,...
432,LAOK,BC UK WoE: Lab-Performance,delete,BC UK WoE: Lab-Performance
433,LAOK,GCG: Lab-Performance,delete,GCG: Lab-Performance
434,LAOK,GCG: TimeTracker,delete,GCG: TimeTracker
435,LAOK,Potential Client: Presale,delete,Potential Client: Presale
436,GOBE,GCG: TimeTracker,delete,GCG: TimeTracker

In [26]:
clients

,name,Update Date,Comment (old name),Old name
0,Abbott,01.07.2025,0,NaN
1,Alrijne,01.07.2025,0,NaN
2,BC Europe&UK,09.12.2025,0,NaN
3,BC FR CHU BRDX,09.12.2025,rename 26.05.2026 (BC Fr Bordeaux),BC Fr Bordeaux
4,BC Global,18.03.2026,rename 26.05.2026 (BC GP),BC GP
5,BC IRL Cork&Kerry,01.07.2025,rename 26.05.2026 (BC Cork&Kerry),BC Cork&Kerry
6,BC IRL NWT,26.05.2026,need to add (new),new
7,BC UK 6S,09.12.2025,rename 26.05.2026 (BC 6S),BC 6S
8,BC UK MSC,01.07.2025,rename 26.05.2026 (BC MSC),BC MSC
9,BC UK SWLP,01.07.2025,rename 26.05.2026 (BC SWLP),BC SWLP
10,BC UK WoE,01.07.2025,rename 26.05.2026 (BC WoE),BC WoE
11,Certe,01.07.2025,0,NaN
12,Dicoon,09.12.2025,0,NaN
13,GCG,01.07.2025,0,NaN
14,Labexa,01.07.2025,0,NaN
15,Potential Client,01.10.2025,0,NaN
16,Regiolab,09.12.2025,0,NaN
17,Siemens-Bernhoven,01.07.2025,0,NaN
18,StreekLab,01.07.2025,0,NaN

In [27]:
nc.loc[nc.user=='BADA']

,id,wid,archived,name,at,creator_id,total_count,user
0,67586844,8752160,False,Abbott,2025-06-29T22:32:51+00:00,11312038,18,BADA
1,67586845,8752160,False,Alrijne,2025-06-29T22:32:51+00:00,11312038,18,BADA
2,68308311,8752160,False,BC Europe&UK,2025-12-09T16:09:51+00:00,11312038,18,BADA
3,68308022,8752160,False,BC FR CHU BRDX,2026-05-26T17:23:17+00:00,11312038,18,BADA
4,68590552,8752160,False,BC Global,2026-05-26T17:23:18+00:00,11312038,18,BADA
5,67590743,8752160,False,BC IRL Cork&Kerry,2026-05-26T17:23:06+00:00,11312038,18,BADA
6,68770357,8752160,False,BC IRL NWT,2026-05-26T20:22:14+00:00,11312038,18,BADA
7,68308021,8752160,False,BC UK 6S,2026-05-26T17:23:06+00:00,11312038,18,BADA
8,67586846,8752160,False,BC UK MSC,2026-05-26T17:23:18+00:00,11312038,18,BADA
9,67586847,8752160,False,BC UK SWLP,2026-05-26T17:23:18+00:00,11312038,18,BADA
10,67586848,8752160,False,BC UK WoE,2026-05-26T17:23:19+00:00,11312038,18,BADA
11,67586854,8752160,False,Bernhoven,2026-08-04T19:03:39+00:00,11312038,18,BADA
12,68307668,8752160,False,Dicoon,2025-12-09T13:41:58+00:00,11312038,18,BADA
13,67586850,8752160,False,GCG,2025-06-29T22:32:57+00:00,11312038,18,BADA
14,67586851,8752160,False,Labexa,2025-06-29T22:33:02+00:00,11312038,18,BADA
15,68316585,8752160,False,Potential Client,2025-12-12T13:26:57+00:00,11312038,18,BADA
16,68308014,8752160,False,Regiolab,2025-12-09T14:58:51+00:00,11312038,18,BADA
17,67586856,8752160,False,StreekLab,2025-06-29T22:33:04+00:00,11312038,18,BADA

In [28]:
clients_diff  = build_diff_entities(clients, nc, 'clients')
clients_diff

    user               name   doing      right_variant
0   BADA              Certe     add              Certe
1   BADA  Siemens-Bernhoven     add  Siemens-Bernhoven
2   AIVI              Certe     add              Certe
3   AIVI  Siemens-Bernhoven     add  Siemens-Bernhoven
4   BODM              Certe     add              Certe
..   ...                ...     ...                ...
59  VAEL          Bernhoven  delete          Bernhoven
60  ANAS          Bernhoven  delete          Bernhoven
61  NIAL          Bernhoven  delete          Bernhoven
62  KAAN          Bernhoven  delete          Bernhoven
63  LAOK          Bernhoven  delete          Bernhoven

[64 rows x 4 columns]

tags_diff = old_tags_to_delete
projects_diff = pd.DataFrame(columns=['user', 'name', 'doing', 'right_variant'])
clients_diff = pd.DataFrame(columns=['user', 'name', 'doing', 'right_variant'])

In [29]:
import pandas as pd

def export_diffs_to_excel(tags_diff: pd.DataFrame,
                          projects_diff: pd.DataFrame,
                          clients_diff: pd.DataFrame,
                          filename: str = './data/diff_tpc.xlsx'):
    
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        tags_diff.to_excel(writer, sheet_name='tags', index=False)
        projects_diff.to_excel(writer, sheet_name='projects', index=False)
        clients_diff.to_excel(writer, sheet_name='clients', index=False)

    print(f"Saved to {filename}")

In [30]:
export_diffs_to_excel(
    tags_diff=tags_diff,
    projects_diff=projects_diff,
    clients_diff=clients_diff,
    filename='./data/diff_tpc.xlsx'
)

Saved to ./data/diff_tpc.xlsx

BC IRL NWT